(function(){
	angular.module("appRouterModule",[])
		.config(["$stateProvider","$urlRouterProvider",
			function($stateProvider,$urlRouterProvider){
			$urlRouterProvider.otherwise("/tab/book");
			$stateProvider
				.state("tab",{
					url:"/tab",
					cache:false,
					templateUrl:"tpl/tab.html"
				})
				.state("tab.book",{
					url:"/book",
					cache:false,
					views:{
						"bookView":{
							templateUrl:"tpl/book.html",
							controller:"bookController"
						}						
					}					
				})
				.state("tab.bookDetail",{
					url:"/bookDetail/:id",
					cache:false,
					views:{
						"bookView":{
							templateUrl:"tpl/bookDetail.html",
							controller:"bookDetailController"
						}						
					}
					
				})
				.state("tab.cart",{
					url:"/cart",
					cache:false,
					views:{
						"cartView":{
							templateUrl:"tpl/cart.html",
							controller:"cartController"
						}
					}
				})
				.state("tab.personal",{
					url:"/personal",
					cache:false,
					views:{
						"personalView":{
							templateUrl:"tpl/personal.html",
							controller:"personalController"
						}
					}
				})
		}])
})();